### ISSUE TITLE
Can't use with Windows

### ISSUE THREAD

**Issue by AdrienNorroy** [jhurliman/homebridge-rfxcom#13]
Hi Every one,

I have a problem using this plugin with Homebridge on a Windows.

Setup Payload:
X-HM://0023ISYWY83P4
Scan this code with your HomeKit app on your iOS device to pair with Homebridge:
Or enter this code with your HomeKit app on your iOS device to pair with Homebri
dge:

    ┌────────────┐
    │ 031-45-154 │
    └────────────┘

[2019-2-22 20:22:52] Homebridge is running on port 51826.
[rfxcom] on USB0 - Error: Opening USB0: File not found
[rfxcom] on USB0 - Cleared command message queue
[2019-2-22 20:22:52] [RFXCom] ERROR: RFXtrx connect fail

I think it comes from this line in Index.js
 this.tty = this.config.tty || '/dev/ttyUSB0'

Which configuration should I set (I m on Windows). In rfxManager, RFX is connected with USB -> COM3

Thank you a lot

Adrien

**Comment by AdrienNorroy** [comment]
Hello, 

Someone can help me ? :(

**Comment by jhurliman** [comment]
Unfortunately, I don't think the underlying https://github.com/rfxcom/node-rfxcom library is compatible with Windows. If you learn otherwise, please let me know and I can add an example in the documentation.
