### ISSUE TITLE
How to use RFXcom with another protocol than RFY ?

### ISSUE THREAD

**Issue by phis5533** [jhurliman/homebridge-rfxcom#14]
Hi, 

I'm using your plugin with my Somfy RFY shutter and it works very cool !

Now, I want to use it with my Chacon/DiO Lightning module, but I don't guess/find the right way of writing the config.json file...
This device use Lightning2, AC protocol to communicate.
It works fine with the windows program RFXMngr.
Can you help me ?
Thx

**Comment by jhurliman** [comment]
This plugin is not going to work with another protocol without a moderately sized overhaul of the code. It uses the https://github.com/rfxcom/node-rfxcom library under the hood, so if that library does not support your device(s) you would need another compatible library and to modify or fork this library to use that other library. Honestly, it might be easier to use this codebase as a reference and start from scratch.
