### ISSUE TITLE
RFXtrx connect fail

### ISSUE THREAD

**Issue by phis5533** [jhurliman/homebridge-rfxcom#2]
Hello @jhurliman ,

I've tried to use my RFXcom with homebridge, but as I launch Homebridge here is the error with RFXcom :

[14/04/2018 à 15:19:13] Loaded plugin: homebridge-rfxcom
[14/04/2018 à 15:19:13] Registering platform 'homebridge-rfxcom.RFXCom'
[14/04/2018 à 15:19:13] ---
[14/04/2018 à 15:19:17] Loaded config.json with 0 accessories and 4 platforms.
[14/04/2018 à 15:19:17] ---
[14/04/2018 à 15:19:17] Loading 4 platforms...
[14/04/2018 à 15:19:20] **[RFXCom] Initializing RFXCom platform...**
[14/04/2018 à 15:19:20] **[RFXCom] ERROR: RFXtrx connect fail**

when I look in my /dev directory I've got an entry for the RFXcom  :

crw-rw-rw-  1 root  wheel            2,   0 14 avr 14:53 tty
crw--w----  1 phv   tty             16,   2 14 avr 15:04 ttys002
crw--w----  1 phv   tty             16,   1 14 avr 15:18 ttys001
crw-rw-rw-  1 root  wheel           21,   6 14 avr 15:18 **tty.usbserial-A12HRIVN**
crw-rw-rw-  1 root  wheel           21,   7 14 avr 15:18 cu.usbserial-A12HRIVN
crw-rw-rw-  1 root  wheel            3,   2 14 avr 15:18 null
crw--w----  1 phv   tty             16,   3 14 avr 15:18 ttys003
crw-rw-rw-  1 root  tty             15,   4 14 avr 15:18 ptmx

My home bridge platform is installed on a Mac under High-Sierra, I can use other platform which work well....

Have you any idea ? Can I force Homebridge to use the right tty ?

Thx for help.

BR
Philippe

**Comment by phis5533** [comment]
I've tried to reinstall the module and I remember I've got a warning :

node-pre-gyp http GET https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/4.0.7/serialport-v4.0.7-node-v59-darwin-x64.tar.gz
node-pre-gyp http 404 https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/4.0.7/serialport-v4.0.7-node-v59-darwin-x64.tar.gz
node-pre-gyp ERR! Tried to download(404): https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/4.0.7/serialport-v4.0.7-node-v59-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for serialport@4.0.7 and node@9.5.0 (node-v59 ABI) (falling back to source compile with node-gyp) 
node-pre-gyp http 404 status code downloading tarball https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/4.0.7/serialport-v4.0.7-node-v59-darwin-x64.tar.gz 
node-pre-gyp verb command build [ 'rebuild' ]

But it ends with :
2 warnings generated.
  SOLINK_MODULE(target) Release/serialport.node
node-pre-gyp info ok 
+ homebridge-rfxcom@1.0.3
added 156 packages from 104 contributors in 41.095s

I don't know what to think.... 
Thx for your help

**Comment by phis5533** [comment]
Hello everybody,

in fact I've updated the node.js file with the right tty port and it works great now !!

Thx a lot it's amazing :-) !!

You can close this issue

**Comment by Kydix** [comment]
I have this same problem, can you explain me how to resolve it ? 

I've follow this tutorial to restart homebridge and i think this is the problem

**Comment by phis5533** [comment]
Hi Kydix,

the way I've fixed it is to edit the /usr/local/lib/node_modules/homebridge-rfxcom/index.js and to add the right TTY port name on the line : 
this.tty = this.config.tty || '/dev/tty.**usbserial-XXXX**
On my Mac I can find the tight name in /dev

Hope it helps !
BR

**Comment by Kydix** [comment]
I have the right port. 

When i install the plugin on a fresh install of homebridge there is no probleme but when i use systemD to automatically start homebridge, i have an error

**Comment by Kydix** [comment]
I used init.d instead of systemd and it's ok now :)
